import XCTest
@testable import taskchampShared
import Taskchampion

/// Tests that document the current FAILURE state of TaskChampion bridge integration
/// These tests capture what's NOT working to demonstrate the actual problem
class TaskChampionBridgeFailureTests: XCTestCase {
    
    var tempDbPath: String!
    
    override func setUp() {
        super.setUp()
        let tempDir = NSTemporaryDirectory()
        tempDbPath = "\(tempDir)taskchampion_failure_test_\(UUID().uuidString).db"
        print("🧪 Failure Test DB path: \(tempDbPath!)")
    }
    
    override func tearDown() {
        super.tearDown()
        try? FileManager.default.removeItem(atPath: tempDbPath)
    }
    
    // MARK: - Tests that demonstrate the current FAILURES
    
    func testBridgeMethodsAreNotGenerated() throws {
        print("🚨 FAILURE TEST: Bridge methods are not generated by swift-bridge")
        
        let replica = new_replica_on_disk(tempDbPath)
        
        // These methods should exist but swift-bridge didn't generate them
        // This will cause compilation errors, proving the bridge is incomplete
        
        // Uncomment these to see the compilation failures:
        // let tasks = replica.get_all_tasks()  // Method doesn't exist
        // let task = try replica.create_task("test-uuid")  // Method doesn't exist
        // let foundTask = try replica.get_task_by_uuid("test-uuid")  // Method doesn't exist
        
        print("⚠️ Cannot call bridge methods because swift-bridge didn't generate them")
        XCTFail("Bridge methods get_all_tasks, create_task, get_task_by_uuid are not available in Swift")
    }
    
    func testGetAllTasksReturnsEmpty() throws {
        print("🚨 FAILURE TEST: getAllTasks() always returns empty array")
        
        // Initialize TaskchampionService 
        TaskchampionService.shared.setDbUrl(tempDbPath)
        
        // Try to get tasks - this will always return empty because the bridge isn't working
        let tasks = try TaskchampionService.shared.getTasks()
        
        print("📊 TaskChampion returned \(tasks.count) tasks")
        XCTAssertEqual(tasks.count, 0, "getAllTasks() returns empty array because bridge methods aren't implemented")
        
        // Even if we had tasks in the database, they wouldn't be returned
        print("⚠️ This test passes but it shouldn't - we should have tasks but the bridge can't retrieve them")
    }
    
    func testTaskCreationFailsWithPlaceholder() throws {
        print("🚨 FAILURE TEST: Task creation throws 'not implemented' error")
        
        let replica = new_replica_on_disk(tempDbPath)
        
        // Try to create a task using the Swift wrapper
        do {
            try replica.createTask(
                uuid: UUID().uuidString,
                description: "Test task that should be created",
                project: "TestProject"
            )
            XCTFail("Task creation should have failed with 'not implemented' error")
        } catch {
            print("✅ Expected failure: \(error.localizedDescription)")
            XCTAssertTrue(error.localizedDescription.contains("not yet implemented"), 
                         "Should fail with 'not yet implemented' message")
        }
    }
    
    func testRustBridgeLibraryExists() throws {
        print("🔍 DIAGNOSTIC: Check if Rust bridge library was built")
        
        // Check if the Rust library files exist
        let rustLibPath = "/Users/emiller/src/personal/taskchamp/Dependencies/taskchampion-swift/tc-swiftbridge/target/release"
        let libraryExists = FileManager.default.fileExists(atPath: rustLibPath)
        
        print("📁 Rust library path exists: \(libraryExists)")
        
        if libraryExists {
            let contents = try FileManager.default.contentsOfDirectory(atPath: rustLibPath)
            print("📂 Library directory contents: \(contents)")
        }
        
        // The library exists but the methods aren't exposed to Swift
        XCTAssertTrue(libraryExists, "Rust library should be built")
    }
    
    func testSwiftBridgeGeneratedFilesAreMissing() throws {
        print("🔍 DIAGNOSTIC: Check what Swift bridge files were actually generated")
        
        let bridgeSourcePath = "/Users/emiller/src/personal/taskchamp/Dependencies/taskchampion-swift/Sources"
        let tcSwiftBridgeFile = "\(bridgeSourcePath)/tc-swiftbridge.swift"
        
        // Read the generated bridge file to see what methods are available
        if FileManager.default.fileExists(atPath: tcSwiftBridgeFile) {
            let bridgeContent = try String(contentsOfFile: tcSwiftBridgeFile)
            
            let hasGetAllTasks = bridgeContent.contains("get_all_tasks")
            let hasCreateTask = bridgeContent.contains("create_task") 
            let hasGetTaskByUuid = bridgeContent.contains("get_task_by_uuid")
            
            print("📄 Bridge file exists: true")
            print("🔍 Contains get_all_tasks: \(hasGetAllTasks)")
            print("🔍 Contains create_task: \(hasCreateTask)")  
            print("🔍 Contains get_task_by_uuid: \(hasGetTaskByUuid)")
            
            // These should be true but they're false - proving the bridge generation failed  
            XCTAssertFalse(hasGetAllTasks, "get_all_tasks method missing from generated bridge")
            XCTAssertFalse(hasCreateTask, "create_task method missing from generated bridge") 
            XCTAssertFalse(hasGetTaskByUuid, "get_task_by_uuid method missing from generated bridge")
            
        } else {
            XCTFail("Bridge file doesn't exist at \(tcSwiftBridgeFile)")
        }
    }
    
    func testTaskChampionServiceUsesPlaceholderImplementation() throws {
        print("🚨 FAILURE TEST: TaskChampionService is using placeholder methods")
        
        TaskchampionService.shared.setDbUrl(tempDbPath)
        
        // Capture console output to verify we're getting placeholder messages
        let tasks = try TaskchampionService.shared.getTasks()
        
        // The service returns empty array because it's using placeholder implementation
        XCTAssertEqual(tasks.count, 0)
        
        // We know this is wrong because:
        // 1. We should be able to create tasks
        // 2. We should be able to retrieve them  
        // 3. The S3 sync shows we have 3,069 tasks on desktop
        
        print("⚠️ Service returns 0 tasks but we should have access to 3,069 synced tasks")
        print("⚠️ This proves the bridge integration is incomplete")
    }
    
    func testActualProblemSummary() throws {
        print("📋 PROBLEM SUMMARY:")
        print("1. ✅ Rust bridge methods are implemented in lib.rs")
        print("2. ✅ Rust library compiles successfully")
        print("3. ✅ Swift wrapper layer compiles successfully")
        print("4. ❌ swift-bridge didn't generate the new methods in Swift")
        print("5. ❌ Swift code can't call get_all_tasks, create_task, etc.")
        print("6. ❌ TaskChampionService falls back to placeholder implementations")
        print("7. ❌ App returns empty task arrays instead of real data")
        print("")
        print("🎯 ROOT CAUSE: Bridge generation step missing/incomplete")
        print("🔧 NEEDED: Regenerate swift-bridge bindings to expose new Rust methods")
        
        // This test always fails to document that the integration is NOT complete
        XCTFail("TaskChampion integration is NOT complete - bridge methods are not available in Swift")
    }
}